image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - format
  - test
  - build

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'

cache:
  key:
    files:
      - $SOURCE_CODE_PATH*.lock.json
  policy: pull-push
  paths:
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY

before_script:
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

Format:
  stage: format
  before_script:
    - dotnet tool install -g dotnet-format
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    - dotnet format --verify-no-changes --no-restore ./PRG2_T07_Team11.sln

Test:
  stage: test
  script:
    - dotnet test --no-restore ./PRG2_T07_Team11.sln

Build:
  stage: build
  script:
    - dotnet build --no-restore ./PRG2_T07_Team11.sln
  